In [172]:
import numpy as np              # hum import krenge 'numpy' mai jo bhi h usse 'np' mai

In [173]:
lst = list(range(1,30))                     # isme hum range bnate h
arr1= np.array(lst)
arr1                            # used as an print statement

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [174]:
arr2 = np.arange(1,30)                      # isme hume range bnane ki need n hoti
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [175]:
arr3=np.array([1,2,3,4,5,6,7,8,9,6,7])
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 7])

In [176]:
arr4=np.zeros((10))                         # hume 0 ko 10 times print krna h
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [177]:
arr5=np.ones(10)                            # hume 1 ko 10 times print krna h
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [178]:
arr6=np.zeros((5,10))                         # print 10 times 0 and also in 5 list
arr6

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [179]:
arr7=np.ones((5,10))                         # hume 0 ko 10 times print krna h
arr7

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [180]:
arr8= np.linspace(1,20,200)                           # give random element in a range  
arr8

array([ 1.        ,  1.09547739,  1.19095477,  1.28643216,  1.38190955,
        1.47738693,  1.57286432,  1.66834171,  1.7638191 ,  1.85929648,
        1.95477387,  2.05025126,  2.14572864,  2.24120603,  2.33668342,
        2.4321608 ,  2.52763819,  2.62311558,  2.71859296,  2.81407035,
        2.90954774,  3.00502513,  3.10050251,  3.1959799 ,  3.29145729,
        3.38693467,  3.48241206,  3.57788945,  3.67336683,  3.76884422,
        3.86432161,  3.95979899,  4.05527638,  4.15075377,  4.24623116,
        4.34170854,  4.43718593,  4.53266332,  4.6281407 ,  4.72361809,
        4.81909548,  4.91457286,  5.01005025,  5.10552764,  5.20100503,
        5.29648241,  5.3919598 ,  5.48743719,  5.58291457,  5.67839196,
        5.77386935,  5.86934673,  5.96482412,  6.06030151,  6.15577889,
        6.25125628,  6.34673367,  6.44221106,  6.53768844,  6.63316583,
        6.72864322,  6.8241206 ,  6.91959799,  7.01507538,  7.11055276,
        7.20603015,  7.30150754,  7.39698492,  7.49246231,  7.58

In [181]:
arr9=np.arange(0,30).reshape(10,3)                  # make an array in a perticular range or make a set
arr9                                                # convert 1D into 2D array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [182]:
arr0=np.arange(0,60).reshape(12,5)
arr0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [183]:
arr10= np.arange(10,50).reshape(8,5)
arr10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

### -> Random numbers array gen

In [184]:
arr_1D=np.random.randint(1,5,9)                     # put random digit in a set but in a range
arr_1D

array([2, 1, 3, 2, 4, 1, 2, 1, 3])

                   This gives 2D array in a random form

In [185]:
arr_2D=np.random.randint(1,5,(5,2))                 # this gives 2D array in a random form
arr_2D

array([[3, 3],
       [1, 1],
       [1, 1],
       [4, 3],
       [4, 1]])

            This gives 3D array in a random form

In [186]:
arr_3D=np.random.random(10)
arr_3D

array([0.27772358, 0.88175687, 0.23435732, 0.42450265, 0.94491375,
       0.57164199, 0.37677036, 0.54094027, 0.86468671, 0.94402741])

                This gives 4D array in a random range

In [187]:
arr_4D=np.random.random((5,10))
arr_4D

array([[0.23801016, 0.2390022 , 0.32614999, 0.40340301, 0.52488328,
        0.74052675, 0.45029503, 0.3027601 , 0.7540202 , 0.79747151],
       [0.20537805, 0.40189462, 0.90427948, 0.35545689, 0.72371574,
        0.82888094, 0.16369682, 0.36510592, 0.28774368, 0.93474532],
       [0.08086767, 0.55917295, 0.18192647, 0.11444799, 0.27436601,
        0.10154984, 0.97518363, 0.8430012 , 0.51592221, 0.87409804],
       [0.5422616 , 0.54099339, 0.11630886, 0.69479479, 0.97504648,
        0.81963019, 0.93678013, 0.21439511, 0.64301984, 0.95963299],
       [0.5320923 , 0.10279766, 0.07320133, 0.96493493, 0.72299986,
        0.51855346, 0.60073055, 0.9407944 , 0.34356776, 0.39285468]])

### -> Array Attributes

In [188]:
arr=np.arange(0,60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [189]:
arr.shape                       

(12, 5)

In [190]:
arr.dtype      #for checking dtaype 

dtype('int64')

In [191]:
arr.ndim          #for checking no. of dimension

2

In [192]:
arr.size               #for  checkig size

60

            function for converting 2D,3D,4D into 1D array

In [193]:
arr.flatten()   

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [194]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [195]:
list_2D = [[1,2,3],[5,6,7]]
list_2D

[[1, 2, 3], [5, 6, 7]]

In [196]:
arr=np.array(list_2D)
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [197]:
arr.shape

(2, 3)

In [198]:
arr.T              #make a transpose

array([[1, 5],
       [2, 6],
       [3, 7]])

In [199]:
arr.T.shape       #make a shape with transpose

(3, 2)

In [201]:
### ->Accessing elements from 1D and 2D array
# for 1d array [row_start:end:step/skip]
# for 2d array [row-start:end:skip/step,column_start:end:skip/step]


In [227]:
arr = np.arange(0,60)                      # isme hume range bnane ki need n hoti
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [203]:
arr[12]               #print value in array

12

In [204]:
arr[0:6]            #print array in range from 0 to 5

array([0, 1, 2, 3, 4, 5])

In [205]:
arr[0:20:2]              #for even no.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [206]:
## 2d array
arr = np.arange(60).reshape(12,5)             
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [207]:
arr[1,1]          #give output as a elemnt of 1row,1column , indexing starts from 0

6

In [208]:
arr[1]          #give output from the 1st row 

array([5, 6, 7, 8, 9])

In [209]:
arr[0:5,1:2]          #take 2nd elemnt from the above outputs, 0 to 5 for rows and 1 to 2 for columns


array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [210]:
arr[1,3:5]           #take from 1column from 7 to 9

array([8, 9])

In [211]:
arr[7:8,4]          #take output from column 7

array([39])

In [212]:
arr[7:8,4][0] = 100         #put value of 7column 5row = 100

In [213]:
arr                                  #39 change into 100

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [214]:
arr[11][-1]

59

In [215]:
arr[-1]           #negative indexing, indexing always start from 0 

array([55, 56, 57, 58, 59])

In [216]:
arr[-1][-1]         #negative indexing take from bottom 1 row and  1column

59

In [217]:
arr[-1,-1]    #same as above

59

In [218]:
arr[11:,-1][0]

59

In [219]:
arr[11:,-1]

array([59])

In [220]:
arr[11,4]

59

### ->For 3d array

In [240]:
arr00 = np.array(np.arange(225).reshape(5,15,3))         #no. of brackets is 3 by this it is 3D array
arr00

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [241]:
arr00.shape

(5, 15, 3)

In [242]:
arr00.shape
#5 --> table
#15 -->row
#3 -->column
###[table,row,column] --> for 3d array

(5, 15, 3)

In [243]:
arr00

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [244]:
arr00[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [249]:
arr00[0][::-1]

array([[42, 43, 44],
       [39, 40, 41],
       [36, 37, 38],
       [33, 34, 35],
       [30, 31, 32],
       [27, 28, 29],
       [24, 25, 26],
       [21, 22, 23],
       [18, 19, 20],
       [15, 16, 17],
       [12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [251]:
arr00[0][::-1,::-1]

array([[44, 43, 42],
       [41, 40, 39],
       [38, 37, 36],
       [35, 34, 33],
       [32, 31, 30],
       [29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])